//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuralNetworik.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuralNetworik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 00000000000001111111100000000000
        ///00000000000001111111111000000000
        ///00000000011011111111111000000000
        ///00000000111111111111111000000000
        ///00000000111111111111111000000000
        ///00000000011111111111111100000000
        ///00000000011111100001111100000000
        ///00000000011111000001111100000000
        ///00000000001111110001111100000000
        ///00000000001111110011111100000000
        ///00000000000111111111111000000000
        ///00000000000001111111111000000000
        ///00000000000001111111111000000000
        ///00000000000001111111110000000000
        ///00000000000000111111100000000000
        ///00 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string optdigits_tes {
            get {
                return ResourceManager.GetString("optdigits_tes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 00000000000001111000000000000000
        ///00000000000011111110000000000000
        ///00000000001111111111000000000000
        ///00000001111111111111100000000000
        ///00000001111111011111100000000000
        ///00000011111110000011110000000000
        ///00000011111110000000111000000000
        ///00000011111110000000111100000000
        ///00000011111110000000011100000000
        ///00000011111110000000011100000000
        ///00000011111100000000011110000000
        ///00000011111100000000001110000000
        ///00000011111100000000001110000000
        ///00000001111110000000000111000000
        ///00000001111110000000000111000000
        ///00 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string optdigits_tra {
            get {
                return ResourceManager.GetString("optdigits_tra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string TrainingDS {
            get {
                return ResourceManager.GetString("TrainingDS", resourceCulture);
            }
        }
    }
}
